# Generated by Django 4.2.21 on 2025-05-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0003_brand_category_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand_name'], name='searchapp_p_brand_n_cea8b4_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category_name'], name='searchapp_p_categor_4a309c_idx'),
        ),
    ]
