# Generated by Django 4.2.21 on 2025-05-17 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0005_brand_brand_name_trigram_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='searchapp_p_brand_n_cea8b4_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='searchapp_p_categor_4a309c_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_name',
        ),
    ]
