# Generated by Django 4.2.21 on 2025-05-17 23:44

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0006_remove_product_searchapp_p_brand_n_cea8b4_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='name_trigram_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
